// GELU activation via ISPA piecewise-linear erf approximation
// Ref: https://www.mdpi.com/2079-9292/14/9/1825
//
// GELU(x) = x * 0.5 * (1 + erf(x/sqrt(2)))
// erf is odd-symmetric: fit PWL on |x|, mirror for sign
// 16 non-uniform segments, breakpoints optimized via EPSS
// Latency: 12 cycles
// Resources: 0 BRAM, 0 DSP from GELU logic itself

module gelu (
  input  wire        clk_i,
  input  wire        valid_i,
  input  wire [15:0] x_i,
  output wire        valid_o,
  output wire [15:0] y_o
);

  // PWL coefficients: auto-generated by gen_gelu_pwl_coeffs.py
  `include "gelu_pwl_coeffs.vh"

  // Coefficient arrays for mux
  wire [15:0] breaks [0:14];
  wire [15:0] slopes [0:15];
  wire [15:0] icepts [0:15];

  assign breaks[ 0] = BREAK_00; assign breaks[ 1] = BREAK_01;
  assign breaks[ 2] = BREAK_02; assign breaks[ 3] = BREAK_03;
  assign breaks[ 4] = BREAK_04; assign breaks[ 5] = BREAK_05;
  assign breaks[ 6] = BREAK_06; assign breaks[ 7] = BREAK_07;
  assign breaks[ 8] = BREAK_08; assign breaks[ 9] = BREAK_09;
  assign breaks[10] = BREAK_10; assign breaks[11] = BREAK_11;
  assign breaks[12] = BREAK_12; assign breaks[13] = BREAK_13;
  assign breaks[14] = BREAK_14;

  assign slopes[ 0] = SLOPE_00; assign slopes[ 1] = SLOPE_01;
  assign slopes[ 2] = SLOPE_02; assign slopes[ 3] = SLOPE_03;
  assign slopes[ 4] = SLOPE_04; assign slopes[ 5] = SLOPE_05;
  assign slopes[ 6] = SLOPE_06; assign slopes[ 7] = SLOPE_07;
  assign slopes[ 8] = SLOPE_08; assign slopes[ 9] = SLOPE_09;
  assign slopes[10] = SLOPE_10; assign slopes[11] = SLOPE_11;
  assign slopes[12] = SLOPE_12; assign slopes[13] = SLOPE_13;
  assign slopes[14] = SLOPE_14; assign slopes[15] = SLOPE_15;

  assign icepts[ 0] = ICEPT_00; assign icepts[ 1] = ICEPT_01;
  assign icepts[ 2] = ICEPT_02; assign icepts[ 3] = ICEPT_03;
  assign icepts[ 4] = ICEPT_04; assign icepts[ 5] = ICEPT_05;
  assign icepts[ 6] = ICEPT_06; assign icepts[ 7] = ICEPT_07;
  assign icepts[ 8] = ICEPT_08; assign icepts[ 9] = ICEPT_09;
  assign icepts[10] = ICEPT_10; assign icepts[11] = ICEPT_11;
  assign icepts[12] = ICEPT_12; assign icepts[13] = ICEPT_13;
  assign icepts[14] = ICEPT_14; assign icepts[15] = ICEPT_15;

  // erf approximation on |x|
  wire        sign_c    = x_i[15];
  wire [15:0] abs_x_c   = {1'b0, x_i[14:0]};
  wire        is_zero_c = (x_i[14:0] == 15'd0);

  // FP16 unsigned comparison: abs_x >= threshold
  // For positive fp16, integer comparison on bits works
  wire saturated_c = (abs_x_c >= SAT_THRESH);

  // 15 parallel comparators -> segment index
  wire [14:0] ge;
  genvar g;
  generate
    for (g = 0; g < 15; g = g + 1) begin : cmp
      assign ge[g] = (abs_x_c >= breaks[g]);
    end
  endgenerate

  // Segment index = count of breakpoints that abs_x exceeds
  // Works because breakpoints are monotonically increasing
  wire [3:0] seg = ge[0] + ge[1] + ge[2] + ge[3] + ge[4] +
                   ge[5] + ge[6] + ge[7] + ge[8] + ge[9] +
                   ge[10] + ge[11] + ge[12] + ge[13] + ge[14];

  wire [15:0] sel_slope_c = slopes[seg];
  wire [15:0] sel_icept_c = icepts[seg];

  // Register segment-mux outputs and specials flags
  reg [15:0] s1_slope, s1_abs_x, s1_icept;
  reg        s1_sign, s1_is_zero, s1_saturated;
  reg        s1_valid;

  always @(posedge clk_i) begin
    s1_slope     <= sel_slope_c;
    s1_abs_x     <= abs_x_c;
    s1_icept     <= sel_icept_c;
    s1_sign      <= sign_c;
    s1_is_zero   <= is_zero_c;
    s1_saturated <= saturated_c;
    s1_valid     <= valid_i;
  end

  // fp16_mul: slope * abs_x
  wire        mul_valid_out;
  wire [15:0] mul_prod;
  fp16_mul u_mul_slope (
    .clk_i(clk_i),
    .valid_i(s1_valid),
    .a_i(s1_slope),
    .b_i(s1_abs_x),
    .valid_o(mul_valid_out),
    .prod_o(mul_prod)
  );

  // Track icept and specials flags through 2-cycle mul
  reg [15:0] mul_icept_r1, mul_icept_r2;
  reg        mul_sign_r1, mul_sign_r2;
  reg        mul_is_zero_r1, mul_is_zero_r2;
  reg        mul_saturated_r1, mul_saturated_r2;
  always @(posedge clk_i) begin
    mul_icept_r1     <= s1_icept;
    mul_icept_r2     <= mul_icept_r1;
    mul_sign_r1      <= s1_sign;
    mul_sign_r2      <= mul_sign_r1;
    mul_is_zero_r1   <= s1_is_zero;
    mul_is_zero_r2   <= mul_is_zero_r1;
    mul_saturated_r1 <= s1_saturated;
    mul_saturated_r2 <= mul_saturated_r1;
  end

  // fp16_add: mul_prod + icept -> erf_pos
  wire        add_icept_valid_out;
  wire [15:0] erf_pos;
  fp16_add u_add_icept (
    .clk_i(clk_i),
    .valid_i(mul_valid_out),
    .a_i(mul_prod),
    .b_i(mul_icept_r2),
    .valid_o(add_icept_valid_out),
    .sum_o(erf_pos)
  );

  // Track specials flags through 3-cycle add
  reg add_sign_r1, add_sign_r2, add_sign_r3;
  reg add_is_zero_r1, add_is_zero_r2, add_is_zero_r3;
  reg add_saturated_r1, add_saturated_r2, add_saturated_r3;
  always @(posedge clk_i) begin
    add_sign_r1      <= mul_sign_r2;
    add_sign_r2      <= add_sign_r1;
    add_sign_r3      <= add_sign_r2;
    add_is_zero_r1   <= mul_is_zero_r2;
    add_is_zero_r2   <= add_is_zero_r1;
    add_is_zero_r3   <= add_is_zero_r2;
    add_saturated_r1 <= mul_saturated_r2;
    add_saturated_r2 <= add_saturated_r1;
    add_saturated_r3 <= add_saturated_r2;
  end

  // Saturated or computed erf, then sign restore (erf is odd-symmetric)
  wire [15:0] erf_pos_final = add_saturated_r3 ? 16'h3C00 : erf_pos;
  wire [15:0] erf_val = (add_sign_r3 && !add_is_zero_r3) ?
                        {1'b1, erf_pos_final[14:0]} : erf_pos_final;

  // Register erf result for next stage
  reg [15:0] erf_r;
  reg        erf_r_valid;
  always @(posedge clk_i) begin
    erf_r       <= erf_val;
    erf_r_valid <= add_icept_valid_out;
  end

  // fp16_add: 1.0 + erf -> one_plus_erf
  wire        add_one_valid_out;
  wire [15:0] one_plus_erf;
  fp16_add u_add_one (
    .clk_i(clk_i),
    .valid_i(erf_r_valid),
    .a_i(16'h3C00),
    .b_i(erf_r),
    .valid_o(add_one_valid_out),
    .sum_o(one_plus_erf)
  );

  // Shift x_i through to align with final multiply
  // Latency from x_i to u_mul_final input: 1 (s1) + 2 (mul) + 3 (add) + 1 (erf_r) + 3 (add_one) = 10
  reg [15:0] x_pipe [0:9];
  integer p;
  always @(posedge clk_i) begin
    x_pipe[0] <= x_i;
    for (p = 1; p < 10; p = p + 1) x_pipe[p] <= x_pipe[p-1];
  end

  wire [15:0] x_aligned = x_pipe[9];

  // half_x = x * 0.5 via exponent decrement; denormals and zero -> 0
  wire [4:0]  x_exp = x_aligned[14:10];
  wire        x_is_denorm = (x_exp == 5'd0);
  wire [15:0] half_x = x_is_denorm ? 16'h0000 :
                       {x_aligned[15], x_exp - 5'd1, x_aligned[9:0]};

  // fp16_mul: half_x * (1 + erf) -> y
  fp16_mul u_mul_final (
    .clk_i(clk_i),
    .valid_i(add_one_valid_out),
    .a_i(half_x),
    .b_i(one_plus_erf),
    .valid_o(valid_o),
    .prod_o(y_o)
  );

endmodule