// GELU activation via ISPA piecewise-linear erf approximation
// Ref: https://www.mdpi.com/2079-9292/14/9/1825
//
// GELU(x) = x * 0.5 * (1 + erf(x/sqrt(2)))
// erf is odd-symmetric: fit PWL on |x|, mirror for sign
// 16 non-uniform segments, breakpoints optimized via EPSS
// Latency: 2 cycles (registered pipeline)
// Resources: 0 BRAM, 0 DSP

module gelu (
  input  wire        clk_i,
  input  wire        valid_i,
  input  wire [15:0] x_i,
  output reg         valid_o,
  output reg  [15:0] y_o
);

  // PWL coefficients: auto-generated by gen_gelu_pwl_coeffs.py
  `include "gelu_pwl_coeffs.vh"

  // Coefficient arrays for mux
  wire [15:0] breaks [0:14];
  wire [15:0] slopes [0:15];
  wire [15:0] icepts [0:15];

  assign breaks[ 0] = BREAK_00; assign breaks[ 1] = BREAK_01;
  assign breaks[ 2] = BREAK_02; assign breaks[ 3] = BREAK_03;
  assign breaks[ 4] = BREAK_04; assign breaks[ 5] = BREAK_05;
  assign breaks[ 6] = BREAK_06; assign breaks[ 7] = BREAK_07;
  assign breaks[ 8] = BREAK_08; assign breaks[ 9] = BREAK_09;
  assign breaks[10] = BREAK_10; assign breaks[11] = BREAK_11;
  assign breaks[12] = BREAK_12; assign breaks[13] = BREAK_13;
  assign breaks[14] = BREAK_14;

  assign slopes[ 0] = SLOPE_00; assign slopes[ 1] = SLOPE_01;
  assign slopes[ 2] = SLOPE_02; assign slopes[ 3] = SLOPE_03;
  assign slopes[ 4] = SLOPE_04; assign slopes[ 5] = SLOPE_05;
  assign slopes[ 6] = SLOPE_06; assign slopes[ 7] = SLOPE_07;
  assign slopes[ 8] = SLOPE_08; assign slopes[ 9] = SLOPE_09;
  assign slopes[10] = SLOPE_10; assign slopes[11] = SLOPE_11;
  assign slopes[12] = SLOPE_12; assign slopes[13] = SLOPE_13;
  assign slopes[14] = SLOPE_14; assign slopes[15] = SLOPE_15;

  assign icepts[ 0] = ICEPT_00; assign icepts[ 1] = ICEPT_01;
  assign icepts[ 2] = ICEPT_02; assign icepts[ 3] = ICEPT_03;
  assign icepts[ 4] = ICEPT_04; assign icepts[ 5] = ICEPT_05;
  assign icepts[ 6] = ICEPT_06; assign icepts[ 7] = ICEPT_07;
  assign icepts[ 8] = ICEPT_08; assign icepts[ 9] = ICEPT_09;
  assign icepts[10] = ICEPT_10; assign icepts[11] = ICEPT_11;
  assign icepts[12] = ICEPT_12; assign icepts[13] = ICEPT_13;
  assign icepts[14] = ICEPT_14; assign icepts[15] = ICEPT_15;

  // Stage 1: erf approximation (combinational)
  wire        sign   = x_i[15];
  wire [15:0] abs_x  = {1'b0, x_i[14:0]};
  wire        is_zero = (x_i[14:0] == 15'd0);

  // FP16 unsigned comparison: abs_x >= threshold
  // For positive fp16, integer comparison on bits works
  wire saturated = (abs_x >= SAT_THRESH);

  // 15 parallel comparators -> segment index
  wire [14:0] ge;
  genvar g;
  generate
    for (g = 0; g < 15; g = g + 1) begin : cmp
      assign ge[g] = (abs_x >= breaks[g]);
    end
  endgenerate

  // Segment index = count of breakpoints that abs_x exceeds
  // Works because breakpoints are monotonically increasing
  wire [3:0] seg = ge[0] + ge[1] + ge[2] + ge[3] + ge[4] +
                   ge[5] + ge[6] + ge[7] + ge[8] + ge[9] +
                   ge[10] + ge[11] + ge[12] + ge[13] + ge[14];

  // Select coefficients
  wire [15:0] sel_slope = slopes[seg];
  wire [15:0] sel_icept = icepts[seg];

  // erf_pos = slope * |x| + intercept
  wire [15:0] product;
  fp16_mul_comb u_mul_slope (
    .a_i(sel_slope),
    .b_i(abs_x),
    .prod_o(product)
  );

  wire [15:0] erf_pos;
  fp16_add_comb u_add_icept (
    .a_i(product),
    .b_i(sel_icept),
    .sum_o(erf_pos)
  );

  // Saturated or computed erf (positive side)
  wire [15:0] erf_pos_final = saturated ? 16'h3C00 : erf_pos; // 1.0 if saturated

  // Sign restore: erf(-x) = -erf(x)
  wire [15:0] erf_val = (sign && !is_zero) ? {1'b1, erf_pos_final[14:0]} : erf_pos_final;

  // Pipeline register: stage 1 -> stage 2
  reg [15:0] erf_r;
  reg [15:0] x_r;
  reg        valid_r;

  always @(posedge clk_i) begin
    erf_r   <= erf_val;
    x_r     <= x_i;
    valid_r <= valid_i;
  end

  // Stage 2: GELU reconstruction (combinational)
  // one_plus_erf = 1.0 + erf_val
  wire [15:0] one_plus_erf;
  fp16_add_comb u_add_one (
    .a_i(16'h3C00),
    .b_i(erf_r),
    .sum_o(one_plus_erf)
  );

  // half_x = x * 0.5 via exponent decrement
  wire [4:0] x_exp = x_r[14:10];
  wire       x_is_denorm = (x_exp == 5'd0);
  // exp-1 for normal numbers; denormals and zero -> 0
  wire [15:0] half_x = (x_is_denorm) ? 16'h0000 :
                        {x_r[15], x_exp - 5'd1, x_r[9:0]};

  // y = half_x * (1 + erf)
  wire [15:0] y_comb;
  fp16_mul_comb u_mul_final (
    .a_i(half_x),
    .b_i(one_plus_erf),
    .prod_o(y_comb)
  );

  // Output register
  always @(posedge clk_i) begin
    y_o     <= y_comb;
    valid_o <= valid_r;
  end

endmodule