`timescale 1ns / 1ps
// Auto-generated by extract_weights.py - DO NOT EDIT

module tb_weight_store;

  reg         clk;
  reg  [ 5:0] tensor_sel;
  reg  [15:0] addr;
  wire [ 7:0] data;
  wire [31:0] scale;

  weight_store uut (
    .clk_i       (clk),
    .tensor_sel_i(tensor_sel),
    .addr_i      (addr),
    .data_o      (data),
    .scale_o     (scale)
  );

  // Clock: 10 ns period
  initial clk = 1'b0;
  always #5 clk = ~clk;

  // Reference arrays compacted to 0..n-1; tsel_lut maps to actual tensor_sel
  reg [7:0]  exp_first [0:18];
  reg [7:0]  exp_last  [0:18];
  reg [15:0] last_addr [0:18];
  reg [5:0]  tsel_lut  [0:18];

  integer errors;
  integer i;
  integer fd;

  initial begin
    // Expected first bytes
    exp_first[ 0] = 8'hfa;  exp_first[ 1] = 8'h5c;
    exp_first[ 2] = 8'hcb;  exp_first[ 3] = 8'h69;
    exp_first[ 4] = 8'h07;  exp_first[ 5] = 8'h62;
    exp_first[ 6] = 8'hc5;  exp_first[ 7] = 8'h72;
    exp_first[ 8] = 8'heb;  exp_first[ 9] = 8'h5d;
    exp_first[10] = 8'hee;  exp_first[11] = 8'h74;
    exp_first[12] = 8'hb5;  exp_first[13] = 8'h74;
    exp_first[14] = 8'hae;  exp_first[15] = 8'h77;
    exp_first[16] = 8'hac;  exp_first[17] = 8'h64;
    exp_first[18] = 8'hcf;

    // Expected last bytes
    exp_last[ 0] = 8'h11;  exp_last[ 1] = 8'h5c;
    exp_last[ 2] = 8'he3;  exp_last[ 3] = 8'h71;
    exp_last[ 4] = 8'hca;  exp_last[ 5] = 8'h66;
    exp_last[ 6] = 8'h01;  exp_last[ 7] = 8'h73;
    exp_last[ 8] = 8'h06;  exp_last[ 9] = 8'h62;
    exp_last[10] = 8'hf9;  exp_last[11] = 8'h72;
    exp_last[12] = 8'hf7;  exp_last[13] = 8'h78;
    exp_last[14] = 8'h27;  exp_last[15] = 8'h78;
    exp_last[16] = 8'h9b;  exp_last[17] = 8'h5c;
    exp_last[18] = 8'haa;

    // Last addresses (depth - 1)
    last_addr[ 0] = 16'd32767;  last_addr[ 1] = 16'd127;
    last_addr[ 2] = 16'd127;  last_addr[ 3] = 16'd127;
    last_addr[ 4] = 16'd127;  last_addr[ 5] = 16'd127;
    last_addr[ 6] = 16'd127;  last_addr[ 7] = 16'd127;
    last_addr[ 8] = 16'd127;  last_addr[ 9] = 16'd127;
    last_addr[10] = 16'd127;  last_addr[11] = 16'd127;
    last_addr[12] = 16'd127;  last_addr[13] = 16'd127;
    last_addr[14] = 16'd127;  last_addr[15] = 16'd127;
    last_addr[16] = 16'd127;  last_addr[17] = 16'd127;
    last_addr[18] = 16'd127;

    // Compact iteration index -> tensor_sel mapping
    tsel_lut[ 0] = 6'd1;  tsel_lut[ 1] = 6'd2;
    tsel_lut[ 2] = 6'd3;  tsel_lut[ 3] = 6'd6;
    tsel_lut[ 4] = 6'd7;  tsel_lut[ 5] = 6'd10;
    tsel_lut[ 6] = 6'd11;  tsel_lut[ 7] = 6'd14;
    tsel_lut[ 8] = 6'd15;  tsel_lut[ 9] = 6'd18;
    tsel_lut[10] = 6'd19;  tsel_lut[11] = 6'd22;
    tsel_lut[12] = 6'd23;  tsel_lut[13] = 6'd26;
    tsel_lut[14] = 6'd27;  tsel_lut[15] = 6'd30;
    tsel_lut[16] = 6'd31;  tsel_lut[17] = 6'd34;
    tsel_lut[18] = 6'd35;

    errors = 0;

    // Open log file
    fd = $fopen("/home/user/red_eyes_is_all_you_need/logs/tb_weight_store.log", "w");

    // Wait for ROMs to initialize
    #20;

    $display("=== Weight Store Testbench ===");
    $fwrite(fd, "=== Weight Store Testbench ===\n");

    for (i = 0; i < 19; i = i + 1) begin
      // Test first byte (addr 0)
      tensor_sel = tsel_lut[i];
      addr       = 16'd0;
      @(posedge clk);
      @(posedge clk);
      #1;

      if (data !== exp_first[i]) begin
        $display("FAIL tensor %0d first: got 0x%02x, expected 0x%02x", tsel_lut[i], data, exp_first[i]);
        $fwrite(fd, "FAIL tensor %0d first: got 0x%02x, expected 0x%02x\n", tsel_lut[i], data, exp_first[i]);
        errors = errors + 1;
      end else begin
        $display("OK   tensor %0d  addr=0  data=0x%02x  scale=0x%08x", tsel_lut[i], data, scale);
        $fwrite(fd, "OK   tensor %0d  addr=0  data=0x%02x  scale=0x%08x\n", tsel_lut[i], data, scale);
      end

      // Test last byte (addr = last_addr)
      addr = last_addr[i];
      @(posedge clk);
      @(posedge clk);
      #1;

      if (data !== exp_last[i]) begin
        $display("FAIL tensor %0d last: got 0x%02x, exp 0x%02x (addr=%0d)",
                 tsel_lut[i], data, exp_last[i], last_addr[i]);
        $fwrite(fd, "FAIL tensor %0d last: got 0x%02x, exp 0x%02x (addr=%0d)\n",
                tsel_lut[i], data, exp_last[i], last_addr[i]);
        errors = errors + 1;
      end else begin
        $display("OK   tensor %0d  addr=%0d  data=0x%02x", tsel_lut[i], last_addr[i], data);
        $fwrite(fd, "OK   tensor %0d  addr=%0d  data=0x%02x\n", tsel_lut[i], last_addr[i], data);
      end
    end

    if (errors == 0) begin
      $display("=== All 38 tests passed ===");
      $fwrite(fd, "=== All 38 tests passed ===\n");
    end else begin
      $display("=== %0d errors out of 38 ===", errors);
      $fwrite(fd, "=== %0d errors out of 38 ===\n", errors);
    end

    $fclose(fd);
    $finish;
  end

endmodule